import {
  hover,
  focus,
  active,
  disabled,
  toColorClass,
  backgroundColor,
  borderColor,
  textColor,
} from './modifier';

export const baseTokens = {
  primary: {
    plainColor: 'joy-primary-500 dark:joy-primary-300',
    plainHoverBg: 'joy-primary-100 dark:joy-primary-800',
    plainActiveBg: 'joy-primary-200 dark:joy-primary-700',
    plainDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedColor: 'joy-primary-500 dark:joy-primary-200',
    outlinedBorder: 'joy-primary-300 dark:joy-primary-700',
    outlinedHoverBg: 'joy-primary-100 dark:joy-primary-800',
    outlinedActiveBg: 'joy-primary-200 dark:joy-primary-700',
    outlinedDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedDisabledBorder: 'joy-neutral-200 dark:joy-neutral-800',
    softColor: 'joy-primary-700 dark:joy-primary-200',
    softBg: 'joy-primary-100 dark:joy-primary-800',
    softHoverBg: 'joy-primary-200 dark:joy-primary-700',
    softActiveColor: 'joy-primary-800 dark:joy-primary-100',
    softActiveBg: 'joy-primary-300 dark:joy-primary-600',
    softDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    softDisabledBg: 'joy-neutral-50 dark:joy-neutral-800',
    solidColor: 'joy-common-white',
    solidBg: 'joy-primary-500',
    solidHoverBg: 'joy-primary-600',
    solidActiveBg: 'joy-primary-700',
    solidDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    solidDisabledBg: 'joy-neutral-100 dark:joy-neutral-800',
  },
  neutral: {
    plainColor: 'joy-neutral-700 dark:joy-neutral-300',
    plainHoverBg: 'joy-neutral-100 dark:joy-neutral-800',
    plainActiveBg: 'joy-neutral-200 dark:joy-neutral-700',
    plainDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedColor: 'joy-neutral-700 dark:joy-neutral-200',
    outlinedBorder: 'joy-neutral-300 dark:joy-neutral-700',
    outlinedHoverBg: 'joy-neutral-100 dark:joy-neutral-800',
    outlinedActiveBg: 'joy-neutral-200 dark:joy-neutral-700',
    outlinedDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedDisabledBorder: 'joy-neutral-200 dark:joy-neutral-800',
    softColor: 'joy-neutral-700 dark:joy-neutral-200',
    softBg: 'joy-neutral-100 dark:joy-neutral-800',
    softHoverBg: 'joy-neutral-200 dark:joy-neutral-700',
    softActiveColor: 'joy-neutral-800 dark:joy-neutral-100',
    softActiveBg: 'joy-neutral-300 dark:joy-neutral-600',
    softDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    softDisabledBg: 'joy-neutral-50 dark:joy-neutral-800',
    solidColor: 'joy-common-white',
    solidBg: 'joy-neutral-500',
    solidHoverBg: 'joy-neutral-600',
    solidActiveBg: 'joy-neutral-700',
    solidDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    solidDisabledBg: 'joy-neutral-100 dark:joy-neutral-800',
    plainHoverColor: 'joy-neutral-900 dark:joy-neutral-300',
  },
  danger: {
    plainColor: 'joy-danger-500 dark:joy-danger-300',
    plainHoverBg: 'joy-danger-100 dark:joy-danger-800',
    plainActiveBg: 'joy-danger-200 dark:joy-danger-700',
    plainDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedColor: 'joy-danger-500 dark:joy-danger-200',
    outlinedBorder: 'joy-danger-300 dark:joy-danger-700',
    outlinedHoverBg: 'joy-danger-100 dark:joy-danger-800',
    outlinedActiveBg: 'joy-danger-200 dark:joy-danger-700',
    outlinedDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedDisabledBorder: 'joy-neutral-200 dark:joy-neutral-800',
    softColor: 'joy-danger-700 dark:joy-danger-200',
    softBg: 'joy-danger-100 dark:joy-danger-800',
    softHoverBg: 'joy-danger-200 dark:joy-danger-700',
    softActiveColor: 'joy-danger-800 dark:joy-danger-100',
    softActiveBg: 'joy-danger-300 dark:joy-danger-600',
    softDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    softDisabledBg: 'joy-neutral-50 dark:joy-neutral-800',
    solidColor: 'joy-common-white',
    solidBg: 'joy-danger-500',
    solidHoverBg: 'joy-danger-600',
    solidActiveBg: 'joy-danger-700',
    solidDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    solidDisabledBg: 'joy-neutral-100 dark:joy-neutral-800',
  },
  success: {
    plainColor: 'joy-success-500 dark:joy-success-300',
    plainHoverBg: 'joy-success-100 dark:joy-success-800',
    plainActiveBg: 'joy-success-200 dark:joy-success-700',
    plainDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedColor: 'joy-success-500 dark:joy-success-200',
    outlinedBorder: 'joy-success-300 dark:joy-success-700',
    outlinedHoverBg: 'joy-success-100 dark:joy-success-800',
    outlinedActiveBg: 'joy-success-200 dark:joy-success-700',
    outlinedDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedDisabledBorder: 'joy-neutral-200 dark:joy-neutral-800',
    softColor: 'joy-success-700 dark:joy-success-200',
    softBg: 'joy-success-100 dark:joy-success-800',
    softHoverBg: 'joy-success-200 dark:joy-success-700',
    softActiveColor: 'joy-success-800 dark:joy-success-100',
    softActiveBg: 'joy-success-300 dark:joy-success-600',
    softDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    softDisabledBg: 'joy-neutral-50 dark:joy-neutral-800',
    solidColor: 'joy-common-white',
    solidBg: 'joy-success-500',
    solidHoverBg: 'joy-success-600',
    solidActiveBg: 'joy-success-700',
    solidDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    solidDisabledBg: 'joy-neutral-100 dark:joy-neutral-800',
  },
  warning: {
    plainColor: 'joy-warning-500 dark:joy-warning-300',
    plainHoverBg: 'joy-warning-100 dark:joy-warning-800',
    plainActiveBg: 'joy-warning-200 dark:joy-warning-700',
    plainDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedColor: 'joy-warning-500 dark:joy-warning-200',
    outlinedBorder: 'joy-warning-300 dark:joy-warning-700',
    outlinedHoverBg: 'joy-warning-100 dark:joy-warning-800',
    outlinedActiveBg: 'joy-warning-200 dark:joy-warning-700',
    outlinedDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    outlinedDisabledBorder: 'joy-neutral-200 dark:joy-neutral-800',
    softColor: 'joy-warning-700 dark:joy-warning-200',
    softBg: 'joy-warning-100 dark:joy-warning-800',
    softHoverBg: 'joy-warning-200 dark:joy-warning-700',
    softActiveColor: 'joy-warning-800 dark:joy-warning-100',
    softActiveBg: 'joy-warning-300 dark:joy-warning-600',
    softDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    softDisabledBg: 'joy-neutral-50 dark:joy-neutral-800',
    solidColor: 'joy-common-white',
    solidBg: 'joy-warning-500',
    solidHoverBg: 'joy-warning-600',
    solidActiveBg: 'joy-warning-700',
    solidDisabledColor: 'joy-neutral-400 dark:joy-neutral-500',
    solidDisabledBg: 'joy-neutral-100 dark:joy-neutral-800',
  },
  focusVisible: 'joy-primary-500',
} as const;

// prettier-ignore
export const colorTokens = {
  primary: {
    plainColor: textColor(baseTokens.primary.plainColor),
    plainHoverBg: hover(backgroundColor(baseTokens.primary.plainHoverBg)),
    plainActiveBg: active(backgroundColor(baseTokens.primary.plainActiveBg)),
    plainDisabledColor: disabled(textColor(baseTokens.primary.plainDisabledColor)),
    outlinedColor: textColor(baseTokens.primary.outlinedColor),
    outlinedBorder: borderColor(baseTokens.primary.outlinedBorder),
    outlinedHoverBg: hover(backgroundColor(baseTokens.primary.outlinedHoverBg)),
    outlinedActiveBg: active(backgroundColor(baseTokens.primary.outlinedActiveBg)),
    outlinedDisabledColor: disabled(textColor(baseTokens.primary.outlinedDisabledColor)),
    outlinedDisabledBorder: disabled(borderColor(baseTokens.primary.outlinedDisabledBorder)),
    softColor: textColor(baseTokens.primary.softColor),
    softBg: backgroundColor(baseTokens.primary.softBg),
    softHoverBg: hover(backgroundColor(baseTokens.primary.softHoverBg)),
    softActiveColor: active(textColor(baseTokens.primary.softActiveColor)),
    softActiveBg: active(backgroundColor(baseTokens.primary.softActiveBg)),
    softDisabledColor: disabled(textColor(baseTokens.primary.softDisabledColor)),
    softDisabledBg: disabled(backgroundColor(baseTokens.primary.softDisabledBg)),
    solidColor: textColor(baseTokens.primary.solidColor),
    solidBg: backgroundColor(baseTokens.primary.solidBg),
    solidHoverBg: hover(backgroundColor(baseTokens.primary.solidHoverBg)),
    solidActiveBg: active(backgroundColor(baseTokens.primary.solidActiveBg)),
    solidDisabledColor: disabled(textColor(baseTokens.primary.solidDisabledColor)),
    solidDisabledBg: disabled(backgroundColor(baseTokens.primary.solidDisabledBg)),
  },
  neutral: {
    plainColor: textColor(baseTokens.neutral.plainColor),
    plainHoverBg: hover(backgroundColor(baseTokens.neutral.plainHoverBg)),
    plainActiveBg: active(backgroundColor(baseTokens.neutral.plainActiveBg)),
    plainDisabledColor: disabled(textColor(baseTokens.neutral.plainDisabledColor)),
    outlinedColor: textColor(baseTokens.neutral.outlinedColor),
    outlinedBorder: borderColor(baseTokens.neutral.outlinedBorder),
    outlinedHoverBg: hover(backgroundColor(baseTokens.neutral.outlinedHoverBg)),
    outlinedActiveBg: active(backgroundColor(baseTokens.neutral.outlinedActiveBg)),
    outlinedDisabledColor: disabled(textColor(baseTokens.neutral.outlinedDisabledColor)),
    outlinedDisabledBorder: disabled(borderColor(baseTokens.neutral.outlinedDisabledBorder)),
    softColor: textColor(baseTokens.neutral.softColor),
    softBg: backgroundColor(baseTokens.neutral.softBg),
    softHoverBg: hover(backgroundColor(baseTokens.neutral.softHoverBg)),
    softActiveColor: active(textColor(baseTokens.neutral.softActiveColor)),
    softActiveBg: active(backgroundColor(baseTokens.neutral.softActiveBg)),
    softDisabledColor: disabled(textColor(baseTokens.neutral.softDisabledColor)),
    softDisabledBg: disabled(backgroundColor(baseTokens.neutral.softDisabledBg)),
    solidColor: textColor(baseTokens.neutral.solidColor),
    solidBg: backgroundColor(baseTokens.neutral.solidBg),
    solidHoverBg: hover(backgroundColor(baseTokens.neutral.solidHoverBg)),
    solidActiveBg: active(backgroundColor(baseTokens.neutral.solidActiveBg)),
    solidDisabledColor: disabled(textColor(baseTokens.neutral.solidDisabledColor)),
    solidDisabledBg: disabled(backgroundColor(baseTokens.neutral.solidDisabledBg)),
    plainHoverColor: hover(textColor(baseTokens.neutral.plainHoverColor)),
  },
  danger: {
    plainColor: textColor(baseTokens.danger.plainColor),
    plainHoverBg: hover(backgroundColor(baseTokens.danger.plainHoverBg)),
    plainActiveBg: active(backgroundColor(baseTokens.danger.plainActiveBg)),
    plainDisabledColor: disabled(textColor(baseTokens.danger.plainDisabledColor)),
    outlinedColor: textColor(baseTokens.danger.outlinedColor),
    outlinedBorder: borderColor(baseTokens.danger.outlinedBorder),
    outlinedHoverBg: hover(backgroundColor(baseTokens.danger.outlinedHoverBg)),
    outlinedActiveBg: active(backgroundColor(baseTokens.danger.outlinedActiveBg)),
    outlinedDisabledColor: disabled(textColor(baseTokens.danger.outlinedDisabledColor)),
    outlinedDisabledBorder: disabled(borderColor(baseTokens.danger.outlinedDisabledBorder)),
    softColor: textColor(baseTokens.danger.softColor),
    softBg: backgroundColor(baseTokens.danger.softBg),
    softHoverBg: hover(backgroundColor(baseTokens.danger.softHoverBg)),
    softActiveColor: active(textColor(baseTokens.danger.softActiveColor)),
    softActiveBg: active(backgroundColor(baseTokens.danger.softActiveBg)),
    softDisabledColor: disabled(textColor(baseTokens.danger.softDisabledColor)),
    softDisabledBg: disabled(backgroundColor(baseTokens.danger.softDisabledBg)),
    solidColor: textColor(baseTokens.danger.solidColor),
    solidBg: backgroundColor(baseTokens.danger.solidBg),
    solidHoverBg: hover(backgroundColor(baseTokens.danger.solidHoverBg)),
    solidActiveBg: active(backgroundColor(baseTokens.danger.solidActiveBg)),
    solidDisabledColor: disabled(textColor(baseTokens.danger.solidDisabledColor)),
    solidDisabledBg: disabled(backgroundColor(baseTokens.danger.solidDisabledBg)),
  },
  success: {
    plainColor: textColor(baseTokens.success.plainColor),
    plainHoverBg: hover(backgroundColor(baseTokens.success.plainHoverBg)),
    plainActiveBg: active(backgroundColor(baseTokens.success.plainActiveBg)),
    plainDisabledColor: disabled(textColor(baseTokens.success.plainDisabledColor)),
    outlinedColor: textColor(baseTokens.success.outlinedColor),
    outlinedBorder: borderColor(baseTokens.success.outlinedBorder),
    outlinedHoverBg: hover(backgroundColor(baseTokens.success.outlinedHoverBg)),
    outlinedActiveBg: active(backgroundColor(baseTokens.success.outlinedActiveBg)),
    outlinedDisabledColor: disabled(textColor(baseTokens.success.outlinedDisabledColor)),
    outlinedDisabledBorder: disabled(borderColor(baseTokens.success.outlinedDisabledBorder)),
    softColor: textColor(baseTokens.success.softColor),
    softBg: backgroundColor(baseTokens.success.softBg),
    softHoverBg: hover(backgroundColor(baseTokens.success.softHoverBg)),
    softActiveColor: active(textColor(baseTokens.success.softActiveColor)),
    softActiveBg: active(backgroundColor(baseTokens.success.softActiveBg)),
    softDisabledColor: disabled(textColor(baseTokens.success.softDisabledColor)),
    softDisabledBg: disabled(backgroundColor(baseTokens.success.softDisabledBg)),
    solidColor: textColor(baseTokens.success.solidColor),
    solidBg: backgroundColor(baseTokens.success.solidBg),
    solidHoverBg: hover(backgroundColor(baseTokens.success.solidHoverBg)),
    solidActiveBg: active(backgroundColor(baseTokens.success.solidActiveBg)),
    solidDisabledColor: disabled(textColor(baseTokens.success.solidDisabledColor)),
    solidDisabledBg: disabled(backgroundColor(baseTokens.success.solidDisabledBg)),
  },
  warning: {
    plainColor: textColor(baseTokens.warning.plainColor),
    plainHoverBg: hover(backgroundColor(baseTokens.warning.plainHoverBg)),
    plainActiveBg: active(backgroundColor(baseTokens.warning.plainActiveBg)),
    plainDisabledColor: disabled(textColor(baseTokens.warning.plainDisabledColor)),
    outlinedColor: textColor(baseTokens.warning.outlinedColor),
    outlinedBorder: borderColor(baseTokens.warning.outlinedBorder),
    outlinedHoverBg: hover(backgroundColor(baseTokens.warning.outlinedHoverBg)),
    outlinedActiveBg: active(backgroundColor(baseTokens.warning.outlinedActiveBg)),
    outlinedDisabledColor: disabled(textColor(baseTokens.warning.outlinedDisabledColor)),
    outlinedDisabledBorder: disabled(borderColor(baseTokens.warning.outlinedDisabledBorder)),
    softColor: textColor(baseTokens.warning.softColor),
    softBg: backgroundColor(baseTokens.warning.softBg),
    softHoverBg: hover(backgroundColor(baseTokens.warning.softHoverBg)),
    softActiveColor: active(textColor(baseTokens.warning.softActiveColor)),
    softActiveBg: active(backgroundColor(baseTokens.warning.softActiveBg)),
    softDisabledColor: disabled(textColor(baseTokens.warning.softDisabledColor)),
    softDisabledBg: disabled(backgroundColor(baseTokens.warning.softDisabledBg)),
    solidColor: textColor(baseTokens.warning.solidColor),
    solidBg: backgroundColor(baseTokens.warning.solidBg),
    solidHoverBg: hover(backgroundColor(baseTokens.warning.solidHoverBg)),
    solidActiveBg: active(backgroundColor(baseTokens.warning.solidActiveBg)),
    solidDisabledColor: disabled(textColor(baseTokens.warning.solidDisabledColor)),
    solidDisabledBg: disabled(backgroundColor(baseTokens.warning.solidDisabledBg)),
  },
  focusVisible: focus(toColorClass(baseTokens.focusVisible, 'outline-')),
};
